apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdfastapi
  labels:
    app: cicdfastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicdfastapi
  template:
    metadata:
      labels:
        app: cicdfastapi
    spec:
      containers:
        - name: cicdfastapi
          image: 637423514597.dkr.ecr.us-east-2.amazonaws.com/cicdfastapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005